---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  #- name: ubuntu-14.04-i386
  #- name: centos-6.6-i386
  - name: debian-8.2-i386
  #- name: fedora-20-i386

suites:
  - name: server
    run_list:
      - recipe[rq_test::default]
    attributes: {"rq_test": {
      "username":     "<%= ENV['RQ_USERNAME'] %>",
      "api_key":      "<%= ENV['RQ_API_KEY'] %>",
      "local_user":   "vagrant",
      "local_group":  "vagrant",
      "rq_ip":        "<%= ENV['RQ_IP'] %>"
      }
    }

